"use client";

import { UserCheck } from "lucide-react";
import { PersonaOutput } from "@/lib/types";

interface PersonaCardProps {
  data: PersonaOutput;
}

export function PersonaCard({ data }: PersonaCardProps) {
  return (
    <div className="paper-card rounded-2xl p-6 border border-black/[0.08] shadow-md space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-black/[0.06] pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-[#A9BCD0]/25 text-[#2B425B]">
            <UserCheck className="h-5 w-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-[#2F2F2F]">Synthetic User Personas</h3>
            <p className="text-xs text-[#666666]">Generated by User Persona Specialist ({data.personas.length} Profiles)</p>
          </div>
        </div>
        <span className="tag-blue px-3 py-1 rounded-full text-xs font-bold">
          Step 04
        </span>
      </div>

      {/* Personas Cards */}
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        {data.personas.map((persona) => (
          <div key={persona.id} className="rounded-xl bg-[#FFFDF9] p-4 border border-black/[0.08] shadow-sm space-y-3 flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-1">
                <h4 className="text-sm font-bold text-[#2F2F2F]">{persona.name}</h4>
                <span className="tag-sage px-2 py-0.5 rounded text-[10px] font-bold">
                  Age {persona.age}
                </span>
              </div>
              <p className="text-xs text-[#6E4935] font-semibold mb-2">{persona.occupation}</p>
              <p className="text-xs text-[#666666] leading-relaxed mb-3">{persona.background}</p>

              <div className="space-y-2 text-xs border-t border-black/[0.06] pt-2">
                <div>
                  <span className="text-[10px] font-bold text-[#3B4D28] uppercase tracking-wider block mb-0.5">Primary Goals</span>
                  <ul className="list-disc list-inside text-[#2F2F2F] space-y-0.5 text-[11px]">
                    {persona.goals.map((g, i) => (
                      <li key={i}>{g}</li>
                    ))}
                  </ul>
                </div>

                <div>
                  <span className="text-[10px] font-bold text-[#6E4935] uppercase tracking-wider block mb-0.5">Pain Points</span>
                  <ul className="list-disc list-inside text-[#2F2F2F] space-y-0.5 text-[11px]">
                    {persona.pain_points.map((p, i) => (
                      <li key={i}>{p}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            <div className="pt-2.5 border-t border-black/[0.06] text-[11px] space-y-1 text-[#666666]">
              <div className="flex justify-between">
                <span>Budget:</span>
                <strong className="text-[#2F2F2F]">{persona.budget}</strong>
              </div>
              <div className="flex justify-between">
                <span>Buying Propensity:</span>
                <strong className="text-[#2F2F2F] capitalize">{persona.buying_behavior}</strong>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
